services:
  mysql:
    image: mysql:8.4
    container_name: stockvision-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: stockvision_root
      MYSQL_DATABASE: stockvision_v2
    ports:
      - "3306:3306"
    volumes:
      - stockvision_mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: stockvision-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.2.2
    container_name: stockvision-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  api:
    build: .
    container_name: stockvision-api
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
      - kafka

volumes:
  stockvision_mysql_data: